# OTBS
binop_separator = "Back"
comment_width = 100
error_on_line_overflow = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = true
imports_granularity = "Crate"
newline_style = "unix"
normalize_doc_attributes = true
reorder_imports = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
version = "Two"
wrap_comments = true
