[package]
name = "wasm"
version = "0.1.0"
authors = ["mark gutenberger <mark-gutenberger@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "=0.2.61"
bumpalo = "=3.8.0"

[lib]
name = "wasm"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true
opt-level = "s"

