// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from './deno.json' assert { type: 'json' };
import * as $0 from './routes/404.tsx';
import * as $1 from './routes/500.tsx';
import * as $2 from './routes/_404.tsx';
import * as $3 from './routes/_500.tsx';
import * as $4 from './routes/api/[url].tsx';
import * as $5 from './routes/api/v1/github/[username].tsx';
import * as $6 from './routes/api/v1/greet/[name].tsx';
import * as $7 from './routes/api/v1/joke.ts';
import * as $8 from './routes/api/v1/random-uuid.ts';
import * as $9 from './routes/api/v1/version.ts';
import * as $10 from './routes/api/v1/wasm.ts';
import * as $11 from './routes/blog.tsx';
import * as $12 from './routes/blog/[slug].tsx';
import * as $13 from './routes/contact.tsx';
import * as $14 from './routes/home.ts';
import * as $15 from './routes/index.tsx';
import * as $16 from './routes/resume.tsx';
import * as $17 from './routes/sitemap.xml.ts';
import * as $$0 from './islands/CalendlyWidget.tsx';
import * as $$1 from './islands/Resume.tsx';
import * as $$2 from './islands/SearchBar.tsx';
import * as $$3 from './islands/TypingCodeBlock.tsx';

const manifest = {
	routes: {
		'./routes/404.tsx': $0,
		'./routes/500.tsx': $1,
		'./routes/_404.tsx': $2,
		'./routes/_500.tsx': $3,
		'./routes/api/[url].tsx': $4,
		'./routes/api/v1/github/[username].tsx': $5,
		'./routes/api/v1/greet/[name].tsx': $6,
		'./routes/api/v1/joke.ts': $7,
		'./routes/api/v1/random-uuid.ts': $8,
		'./routes/api/v1/version.ts': $9,
		'./routes/api/v1/wasm.ts': $10,
		'./routes/blog.tsx': $11,
		'./routes/blog/[slug].tsx': $12,
		'./routes/contact.tsx': $13,
		'./routes/home.ts': $14,
		'./routes/index.tsx': $15,
		'./routes/resume.tsx': $16,
		'./routes/sitemap.xml.ts': $17,
	},
	islands: {
		'./islands/CalendlyWidget.tsx': $$0,
		'./islands/Resume.tsx': $$1,
		'./islands/SearchBar.tsx': $$2,
		'./islands/TypingCodeBlock.tsx': $$3,
	},
	baseUrl: import.meta.url,
	config,
};

export default manifest;
