import { TailwindPluginOptions } from '$fresh/plugins/tailwind/types.ts';
import colors from 'tailwindcss/colors';

export default {
	future: { // ignore error, bug within the framework plugin
		hoverOnlyWhenSupported: true,
	},
	content: [
		'{routes,islands,components}/**/*.{ts,tsx}',
	],
	darkMode: 'selector',
	theme: {
		extend: {
			aspectRatio: {
				'pdf': '8.5 / 11',
			},
			colors: {
				'gray': colors.neutral,
			},
			borderWidth: {
				DEFAULT: '1px',
				'0': '0',
				'2': '2px',
				'3': '3px',
				'4': '4px',
				'6': '6px',
				'8': '8px',
			},
			fontFamily: {
				sedwick: ['Sedgwick Ave Display', 'cursive'],
				sans: [
					'"Source Sans Pro"',
					'Poppins',
					'"Open Sans"',
					'Roboto',
					'Arial',
					'sans-serif',
					'ui-sans-serif',
					'system-ui',
					'-apple-system',
					'BlinkMacSystemFont',
					'"Segoe UI"',
					'Inter',
					'"Helvetica Neue"',
					'"Noto Sans"',
					'"Apple Color Emoji"',
					'"Segoe UI Emoji"',
					'"Segoe UI Symbol"',
					'"Noto Color Emoji"',
				],
				serif: [
					'ui-serif',
					'Georgia',
					'Cambria',
					'"Times New Roman"',
					'Times',
					'serif',
				],
				mono: [
					'Fira Code',
					'ui-monospace',
					'SFMono-Regular',
					'Menlo',
					'Monaco',
					'Consolas',
					'"Liberation Mono"',
					'"Courier New"',
					'monospace',
				],
				fira: [
					'Fira Sans',
					'ui-sans-serif',
					'system-ui',
					'-apple-system',
					'BlinkMacSystemFont',
					'"Segoe UI"',
					'Roboto',
					'"Helvetica Neue"',
					'Arial',
					'"Noto Sans"',
					'sans-serif',
					'"Apple Color Emoji"',
					'"Segoe UI Emoji"',
					'"Segoe UI Symbol"',
					'"Noto Color Emoji"',
				],
			},
		},
	},
} satisfies TailwindPluginOptions;
