import { Options } from '$fresh/plugins/twind.ts';
import * as colors from 'twind/colors';

export default {
	selfURL: import.meta.url,
	mode: 'silent',
	// darkMode: 'class',
	theme: {
		extend: {
			colors: {
				'transparent': 'transparent',
				'current': 'currentColor',
				'amber': colors.amber,
				'black': colors.black,
				'blue': colors.blue,
				'blueGray': colors.blueGray,
				'coolGray': colors.coolGray,
				'cyan': colors.cyan,
				'emerald': colors.emerald,
				'fuchsia': colors.fuchsia,
				'gray': colors.gray,
				'green': colors.green,
				'indigo': colors.indigo,
				'lightBlue': colors.lightBlue,
				'lime': colors.lime,
				'orange': colors.orange,
				'pink': colors.pink,
				'purple': colors.purple,
				'red': colors.red,
				'rose': colors.rose,
				'sky': colors.sky,
				'teal': colors.teal,
				'trueGray': colors.trueGray,
				'violet': colors.violet,
				'warmGray': colors.warmGray,
				'white': colors.white,
				'yellow': colors.yellow,
			},
			borderWidth: {
				DEFAULT: '1px',
				'0': '0',
				'2': '2px',
				'3': '3px',
				'4': '4px',
				'6': '6px',
				'8': '8px',
			},
			fontFamily: {
				sans: [
					'Fira',
					'Fira Sans',
					'Inter',
					'ui-sans-serif',
					'system-ui',
					'-apple-system',
					'BlinkMacSystemFont',
					'"Segoe UI"',
					'Roboto',
					'"Helvetica Neue"',
					'Arial',
					'"Noto Sans"',
					'sans-serif',
					'"Apple Color Emoji"',
					'"Segoe UI Emoji"',
					'"Segoe UI Symbol"',
					'"Noto Color Emoji"',
				],
				serif: [
					'ui-serif',
					'Georgia',
					'Cambria',
					'"Times New Roman"',
					'Times',
					'serif',
				],
				mono: [
					'Fira Code',
					'ui-monospace',
					'SFMono-Regular',
					'Menlo',
					'Monaco',
					'Consolas',
					'"Liberation Mono"',
					'"Courier New"',
					'monospace',
				],
				fira: [
					'Fira Sans',
					'ui-sans-serif',
					'system-ui',
					'-apple-system',
					'BlinkMacSystemFont',
					'"Segoe UI"',
					'Roboto',
					'"Helvetica Neue"',
					'Arial',
					'"Noto Sans"',
					'sans-serif',
					'"Apple Color Emoji"',
					'"Segoe UI Emoji"',
					'"Segoe UI Symbol"',
					'"Noto Color Emoji"',
				],
			},
		},
	},
} as Options;

export * from 'twind';
