// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/404.tsx';
import * as $_500 from './routes/500.tsx';
import * as $_404_1 from './routes/_404.tsx';
import * as $_500_1 from './routes/_500.tsx';
import * as $_app from './routes/_app.tsx';
import * as $blog from './routes/blog.tsx';
import * as $blog_slug_ from './routes/blog/[slug].tsx';
import * as $blog_feed_rss from './routes/blog/feed.rss.ts';
import * as $home from './routes/home.ts';
import * as $index from './routes/index.tsx';
import * as $license from './routes/license.tsx';
import * as $privacy_policy from './routes/privacy-policy.tsx';
import * as $resume from './routes/resume.tsx';
import * as $sitemap_xml from './routes/sitemap.xml.ts';
import * as $ColorMode from './islands/ColorMode.tsx';
import * as $Resume from './islands/Resume.tsx';
import { type Manifest } from '$fresh/server.ts';

const manifest = {
	routes: {
		'./routes/404.tsx': $_404,
		'./routes/500.tsx': $_500,
		'./routes/_404.tsx': $_404_1,
		'./routes/_500.tsx': $_500_1,
		'./routes/_app.tsx': $_app,
		'./routes/blog.tsx': $blog,
		'./routes/blog/[slug].tsx': $blog_slug_,
		'./routes/blog/feed.rss.ts': $blog_feed_rss,
		'./routes/home.ts': $home,
		'./routes/index.tsx': $index,
		'./routes/license.tsx': $license,
		'./routes/privacy-policy.tsx': $privacy_policy,
		'./routes/resume.tsx': $resume,
		'./routes/sitemap.xml.ts': $sitemap_xml,
	},
	islands: {
		'./islands/ColorMode.tsx': $ColorMode,
		'./islands/Resume.tsx': $Resume,
	},
	baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
