// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from './routes/404.tsx';
import * as $1 from './routes/500.tsx';
import * as $2 from './routes/_404.tsx';
import * as $3 from './routes/_500.tsx';
import * as $4 from './routes/_app.tsx';
import * as $5 from './routes/blog.tsx';
import * as $6 from './routes/blog/[slug].tsx';
import * as $7 from './routes/blog/feed.rss.ts';
import * as $8 from './routes/home.ts';
import * as $9 from './routes/index.tsx';
import * as $10 from './routes/license.tsx';
import * as $11 from './routes/privacy-policy.tsx';
import * as $12 from './routes/resume.tsx';
import * as $13 from './routes/sitemap.xml.ts';
import * as $$0 from './islands/ColorMode.tsx';
import * as $$1 from './islands/Resume.tsx';

const manifest = {
	routes: {
		'./routes/404.tsx': $0,
		'./routes/500.tsx': $1,
		'./routes/_404.tsx': $2,
		'./routes/_500.tsx': $3,
		'./routes/_app.tsx': $4,
		'./routes/blog.tsx': $5,
		'./routes/blog/[slug].tsx': $6,
		'./routes/blog/feed.rss.ts': $7,
		'./routes/home.ts': $8,
		'./routes/index.tsx': $9,
		'./routes/license.tsx': $10,
		'./routes/privacy-policy.tsx': $11,
		'./routes/resume.tsx': $12,
		'./routes/sitemap.xml.ts': $13,
	},
	islands: {
		'./islands/ColorMode.tsx': $$0,
		'./islands/Resume.tsx': $$1,
	},
	baseUrl: import.meta.url,
};

export default manifest;
