name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

        # TODO: add a build step here

      - name: Build
        run: |
          curl -sSf https://sh.rustup.rs | sh -s -- -y --nightly-toolchain 1.65.0
          export PATH="$PATH:/home/rust/.cargo/bin"
          deno install -Afq -n deno_bindgen https://deno.land/x/deno_bindgen/cli.ts
          deno task build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "gutenfries"
          entrypoint: "./main.ts"
