name: Deploy

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build
        run: "deno task build"

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "gutenfries"
          entrypoint: "./main.ts"
